version: "3"
services:
  mapartotheque:
    cpus: 4 # this change is enough for me
    container_name: mapartotheque
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8090:8090"
    # stdin_open: true
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
